#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

[[ -f $XDG_CONFIG_HOME/X11/Xresources ]] && xrdb -load $XDG_CONFIG_HOME/X11/Xresources
# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


session="${1}"


echo "session variable: $session" >> ~/xinit.log

# Laptop options
if [ "$session" != "plasma" ]
then
    setxkbmap -option caps:escape_shifted_capslock
    brightnessctl -q set 50%
    xinput set-prop 'ELAN1205:00 04F3:30E9 Touchpad' 'libinput Tapping Enabled' 1
    xsetroot -cursor_name left_ptr

    gnome-keyring-daemon --start --daemonize
    udiskie &
    nmgui &
    dunst &
    sxhkd &
    touchegg --daemon &
    touchegg &
    pipewire &
    pipewire-pulse &
    wireplumber &
    redshift -l '45.72:13.48' &
fi

case "$session" in
    "dwm") $HOME/.local/scripts/bar &
	  picom --config $HOME/.config/picom/picom.conf &
	  feh --no-fehbg --bg-fill /home/gianluca/media/pics/wallpapers/crystal_cave.png
	  exec dwm ;;
    "gnome") exec gnome-session ;;
    "xfce") exec xfce4-session ;;
    "plasma") export DESKTOP_SESSION=plasma
              exec startplasma-x11 ;;
    "plasma-nvidia") export DESKTOP_SESSION=plasma
                    exec startplasma-x11 ;;
    "awesome") picom --config $HOME/.config/picom/picom.conf &
	      feh --no-fehbg --bg-fill /home/gianluca/media/pics/wallpapers/crystal_cave.png
               exec awesome ;;
    "xmonad") picom --config $HOME/.config/picom/picom.conf &
              feh --no-fehbg --bg-fill /home/gianluca/media/pics/wallpapers/crystal_cave.png
              exec xmonad ;;
esac
