#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

[[ -f $XDG_CONFIG_HOME/X11/Xresources ]] && xrdb -load $XDG_CONFIG_HOME/X11/Xresources
# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


session="${1}"


# echo "session variable: $session" >> ~/xinit.log

# Laptop options
# setxkbmap -option caps:escape_shifted_capslock
# brightnessctl -q set 50%

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
sxhkd &
redshift -l '45.72:13.48' &

case "$session" in
    "dwm") $HOME/.local/scripts/bar &
	       picom --config $HOME/.config/picom/picom.conf &
	       feh --no-fehbg --bg-fill /home/gianluca/media/pics/wallpapers/crystal_cave.png
	       exec dwm ;;
    "gnome") exec gnome-session ;;
    "xfce") exec xfce4-session ;;
esac
